export const EVL_GET_EVENTS_LIST = "EVL_GET_EVENTS_LIST";
export const EVL_EVENTS_LIST_ERR = "EVL_EVENTS_LIST_ERR";
export const EVL_GET_EVENT_DETAIL = "EVL_GET_EVENT_DETAIL";
export const EVL_LOAD_DATA = "EVL_LOAD_DATA";