const OPEN_MODAL_ERROR = "OPEN_MODAL_ERROR";
const CLOSE_MODAL_ERROR = "CLOSE_MODAL_ERROR";
const OPEN_MODAL_SUCCESS = "OPEN_MODAL_SUCCESS";
const CLOSE_MODAL_SUCCESS = "CLOSE_MODAL_SUCCESS";
export default {
    OPEN_MODAL_ERROR,
    CLOSE_MODAL_ERROR,
    OPEN_MODAL_SUCCESS,
    CLOSE_MODAL_SUCCESS,
}