export const GET_NOTICES = "GET_NOTICES";
export const GET_NOTICES_SUCCESS = "GET_NOTICES_SUCCESS";
export const GET_NOTICES_FAIL = "GET_NOTICES_FAIL";
export const GET_NOTICE_DETAIL = "GET_NOTICE_DETAIL";