export const S01_HANDLE_LOGIN = "S01_HANDLE_LOGIN";
export const S01_LOGIN_SUCCESS = "S01_LOGIN_SUCCESS";
export const S01_LOGIN_FAILURE = "S01_LOGIN_FAILURE";
export const S01_SET_TOKEN = "S01_SET_TOKEN";
export const S01_LOGOUT = "S01_LOGOUT";
