export const HANDLE_LOGIN = "HANDLE_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";
export const CLOSE_STANDBY_SCREEN = "CLOSE_STANDBY_SCREEN";
